name: inpaint
channels:
- defaults
- pytorch
- conda-forge
dependencies:
- einops=0.3.2
- jupyter=1.0.0
- matplotlib=3.4.2
- numpy=1.20.2
- pillow=8.3.1
- pip=21.2.4
- python=3.8
- pytorch=1.10.1
- setuptools=52.0.0
- torchvision=0.11.2
- yaml=0.2.5
- pip:
  - flake8==3.9.2
  - pre-commit==2.14.0
  - pytest==6.2.4
  - pyflakes==2.3.1
  - opencv-python==4.5.3.56
  - tensorboard==2.6.0
  - tensorboard-data-server==0.6.1
  - tensorboard-plugin-wit==1.8.0
  - torchmetrics==0.5.0
  - tox==3.14.0
