name: inpaint
channels:
- defaults
- pytorch
- conda-forge
dependencies:
- einops=0.3
- jupyter=1.0
- matplotlib=3.4
- numpy=1.20
- pillow=8.3
- pip=21.2
- python=3.8
- pytorch=1.10
- setuptools=52.0
- torchvision=0.11.2
- yaml=0.2
- pip:
  - flake8==3.9
  - pre-commit==2.14
  - pytest==6.2
  - pyflakes==2.3
  - opencv-python==4.5.3.56
  - scikit-image
  - tensorboard
  - tensorboard-data-server
  - tensorboard-plugin-wit
  - torchmetrics
  - tox
